import type { ContactCard } from "./types"

export const mockCards: ContactCard[] = [
  {
    id: "1",
    name: "Sarah Chen",
    title: "Software Engineer",
    company: "Stripe",
    email: "s.chen@stripe.com",
    phone: "+1 (415) 555-0192",
    website: "stripe.com",
    category: "Tech",
    accent: "#3b82f6",
    aiDescription: "Stripe builds payment infrastructure for the internet, enabling millions of businesses to accept money online. Known for its developer-first APIs and financial services platform.",
    userNotes: "",
    capturedAt: "2025-04-10T09:14:00Z",
  },
  {
    id: "2",
    name: "Marcus Reed",
    title: "Product Designer",
    company: "Figma",
    email: "marcus.reed@figma.com",
    phone: "+1 (628) 555-0347",
    website: "figma.com",
    category: "Design",
    accent: "#f59e0b",
    aiDescription: "Figma is a collaborative interface design tool used by product teams worldwide. It runs entirely in the browser, enabling real-time co-design across distributed teams.",
    userNotes: "Met at Config 2025. Interested in design systems collab.",
    capturedAt: "2025-04-22T14:30:00Z",
  },
  {
    id: "3",
    name: "Priya Patel",
    title: "VP of Finance",
    company: "Goldman Sachs",
    email: "ppatel@gs.com",
    phone: "+1 (212) 555-0804",
    website: "goldmansachs.com",
    category: "Finance",
    accent: "#10b981",
    aiDescription: "Goldman Sachs is a leading global investment banking and financial services company. It serves corporations, financial institutions, governments, and individuals worldwide.",
    userNotes: "",
    capturedAt: "2025-03-05T11:00:00Z",
  },
  {
    id: "4",
    name: "James Whitmore",
    title: "Partner",
    company: "Morrison & Foerster",
    email: "jwhitmore@mofo.com",
    phone: "+1 (415) 555-0561",
    website: "mofo.com",
    category: "Legal",
    accent: "#8b5cf6",
    aiDescription: "Morrison & Foerster is a global law firm known for its work in technology, life sciences, and finance. It advises leading companies on complex transactions and litigation.",
    userNotes: "IP counsel referral from David. Follow up re: trademark filing.",
    capturedAt: "2025-02-17T16:45:00Z",
  },
  {
    id: "5",
    name: "Elena Vargas",
    title: "Head of Growth",
    company: "HubSpot",
    email: "e.vargas@hubspot.com",
    phone: "+1 (617) 555-0239",
    website: "hubspot.com",
    category: "Marketing",
    accent: "#ec4899",
    aiDescription: "HubSpot provides an all-in-one CRM platform for marketing, sales, and customer service. Widely used by SMBs and mid-market companies to automate and track customer journeys.",
    userNotes: "",
    capturedAt: "2025-05-01T10:20:00Z",
  },
  {
    id: "6",
    name: "Tomás Reyes",
    title: "Founder & Creative Director",
    company: "Aperture Studio",
    email: "tomas@aperture.studio",
    phone: "+1 (503) 555-0718",
    website: "aperture.studio",
    category: "Design",
    accent: "#f59e0b",
    aiDescription: "Aperture Studio is a boutique brand identity and motion design agency working with early-stage startups and consumer brands. Known for bold visual systems and launch campaigns.",
    userNotes: "Potential contractor for rebrand project. Strong portfolio.",
    capturedAt: "2025-04-30T13:10:00Z",
  },
  {
    id: "7",
    name: "Naomi Brooks",
    title: "Senior Infrastructure Engineer",
    company: "Vercel",
    email: "n.brooks@vercel.com",
    phone: "+1 (510) 555-0043",
    website: "vercel.com",
    category: "Tech",
    accent: "#3b82f6",
    aiDescription: "Vercel is a cloud platform for frontend developers, offering instant global deployments and serverless functions. The company also develops Next.js, the popular React framework.",
    userNotes: "",
    capturedAt: "2025-03-28T09:55:00Z",
  },
  {
    id: "8",
    name: "David Kim",
    title: "Financial Advisor",
    company: "BlackRock",
    email: "david.kim@blackrock.com",
    phone: "+1 (212) 555-0392",
    website: "blackrock.com",
    category: "Finance",
    accent: "#10b981",
    aiDescription: "BlackRock is the world's largest asset management firm, overseeing trillions in assets across equities, fixed income, multi-asset, and alternative investments.",
    userNotes: "Intro from Priya. Handles Series B+ treasury strategy.",
    capturedAt: "2025-01-14T15:00:00Z",
  },
  {
    id: "9",
    name: "Claire Fontaine",
    title: "Brand Director",
    company: "Mailchimp",
    email: "cfontaine@mailchimp.com",
    phone: "+1 (404) 555-0657",
    website: "mailchimp.com",
    category: "Marketing",
    accent: "#ec4899",
    aiDescription: "Mailchimp is an all-in-one email marketing and automation platform used by small businesses globally. It offers audience management, campaign analytics, and creative tooling.",
    userNotes: "",
    capturedAt: "2025-05-08T12:30:00Z",
  },
]
